### PR TITLE
Fix: database

### PR DESCRIPTION
**Pull request by AngeloTadeucci**
Following MySQL guidelines, changed all columns and tables to lowercase and use snake case. 
Also fix an issue where linux users couldn't start the emulator.

### CODE REVIEW

**Review by Sparkymod — APPROVED** [review]
LGTM

**Review by darkvergus — COMMENTED** [review]
Any reason as to why you're not doing expression body in some of the reads?

**Comment by sgessa** [comment]
Tested on Linux, it's working fine

**Review by sgessa — APPROVED** [review]
LGTM

**Pull request merged**
