### PR TITLE
Implementing item rewards upon accepting quests.

### PR DESCRIPTION
**Pull request by icegabriel**
Hello, I discovered this project today and encountered problems proceeding as the Strike class, because I need the red herbs given upon accepting the Chairwoman Jayce quest.

### CODE REVIEW

**Review by AngeloTadeucci — APPROVED** [review]
Looking good, whats your discord?

**Comment by AngeloTadeucci** [comment]
Looks like there is some formatting issues, check the actions

**Comment by icegabriel** [comment]
Thanks! My Discord username is ICELANDIA#0866. The Rider IDE has caused this weird spacing issue 😞.

**Comment by AngeloTadeucci** [comment]
> Thanks! My Discord username is ICELANDIA#0866. The Rider IDE has caused this weird spacing issue 😞.

Rider to be like that xD

**Pull request merged**
